version: '3'

services:
  db:
    image: postgres:9.6
    ports:
      - "5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - ./my_app:/my_app
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD:
      DATABASE_PORT: 5432
      DATABASE_HOST: db
